DROP TABLE IF EXISTS USER;
CREATE TABLE USER(
ID VARCHAR (500) PRIMARY KEY NOT NULL,
NAME VARCHAR (50),
EMAIL VARCHAR (50),
PASSWORD VARCHAR (50),
CREATED DATE,
MODIFIED DATE,
LAST_LOGIN DATE,
TOKEN VARCHAR (500),
ISACTIVE BOOLEAN
);


DROP TABLE IF EXISTS PHONE;
CREATE TABLE PHONE(
ID VARCHAR (500) PRIMARY KEY NOT NULL,
ID_USER VARCHAR (500) REFERENCES USER (ID),
NUMBER VARCHAR (50),
CITY_CODE VARCHAR (50),
COUNTRY_CODE VARCHAR (50) 
);