DROP TABLE IF EXISTS USER;
CREATE TABLE USER(
ID VARCHAR (500) PRIMARY KEY NOT NULL,
NAME VARCHAR (50),
PASSWORD VARCHAR (50),
CREATED DATE,
MODIFIED DATE,
LAST_LOGIN DATE,
TOKEN VARCHAR (50),
ISACTIVE BOOLEAN
);


DROP TABLE IF EXISTS PHONE;
CREATE TABLE PHONE(
ID VARCHAR (500) PRIMARY KEY NOT NULL,
IDUSER VARCHAR (500) REFERENCES USER (ID),
NUMBER VARCHAR (50),
CITYCODE VARCHAR (50),
COUNTRYCODE VARCHAR (50) 
);